name: raindrops
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: Raindrops
  source-dirs: src
  dependencies:
    - containers
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - raindrops
      - hspec
