name: wordy
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: WordProblem
  source-dirs: src
  dependencies:
    - parsec
    - either
    - extra
    - mtl
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - hspec
